name = "collections"
author = "Jason Christopherson"
license = "BSD-3"
description = "A group of generic collections for modern Fortran."
homepage = "https://github.com/jchristopherson/collections"
keywords = ["generic list"]

[dependencies]
ferror = {git = "https://github.com/jchristopherson/ferror"}

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src"

[install]
library = true

[[test]]
name = "list_test"
source-dir = "tests"
main = "list_test.f90"

[[test]]
name = "linked_list_test"
source-dir = "tests"
main = "linked_list_test.f90"

[[example]]
name = "list_example"
source-dir = "examples"
main = "list_example.f90"

[[example]]
name = "linked_list_example"
source-dir = "examples"
main = "linked_list_example.f90"
