name = "collections"
version = "1.4.2"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2022-2023, Jason Christopherson"
description = "A set of types supporting collections in Fortran."
homepage = "https://github.com/jchristopherson/collections"

[library]
source-dir = "src"

[dependencies]
ferror = { git = "https://github.com/jchristopherson/ferror/git" }

[[test]]
name = "collections_test.f90"
source-dir = "test"
main = "collections_test.f90"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false